### ISSUE TITLE
Plugin URL occasionally drops admin upon clicking "+" symbol

### ISSUE THREAD

**Issue by furioursus** [nystudio107/craft-retour#18]
I can't recreate it every time; it seems to be on a per-error basis, but I'm getting an error where the "admin" part of the url occasionally drops out of the url bar and ironically creates a new 404 entry of its own. I can't reproduce it, but it will pop up at the most inopportune times!

![oakland-error](https://user-images.githubusercontent.com/366427/45456942-91636400-b6a1-11e8-8eb3-8c0a7c32872f.gif)

**Comment by khalwat** [comment]
Should be an easy fix.

**Comment by khalwat** [comment]
Fixed in https://github.com/nystudio107/craft-retour/releases/tag/3.0.2

**Comment by furioursus** [comment]
Just updated and it looks like the urls are now `/admin/retour/add-redirect/%2Fuploads%2Fnews%2Foakland.jpg` and erroring out.

**Comment by baileydoestech** [comment]
Seeing the same issue as well (updated to 3.0.2)

![image](https://user-images.githubusercontent.com/3185073/45487894-94b92700-b757-11e8-9cb0-f51a6da907c4.png)

**Comment by furioursus** [comment]
Latest version of 3.0.4 and I'm still getting urls like

`/admin/retour/add-redirect/%2Fads.txt` on a fresh install of Chrome: 

<img width="1042" alt="screen shot 2018-09-14 at 8 01 42 am" src="https://user-images.githubusercontent.com/366427/45558434-c0d6b580-b7f4-11e8-97d6-d1dc280027d9.png">
