### ISSUE TITLE
Retour not showing statistics. Possible Vue error

### ISSUE THREAD

**Issue by darylknight** [nystudio107/craft-retour#191]
### Describe the bug

We launched a new site yesterday. The first time I looked at Retour today there were 1000 404s (the maximum). I selected everything ending in `.axd` (which gave me 10 results) and deleted them. Now Retour isn't showing any statistics at all, but it's still showing "10 statistics:" after clearing caches, and new 404s don't appear - the list is empty (even if I visit a deliberate 404 on the front end).

![image](https://user-images.githubusercontent.com/1250017/124745587-a7183700-df28-11eb-82d5-7c31978ad5a5.png)

I'm trying to track down what might be causing it, and the only thing I can see that might be vaguely relevant is this in the console logs:

![image](https://user-images.githubusercontent.com/1250017/124745388-6f10f400-df28-11eb-9588-16b22f4ec6c8.png)

Retour 3.1.55

**Comment by darylknight** [comment]
Update - looks like 404s and stats are being stored in the database correctly, but the Statistics and Redirects pages won't show them.

The Redirects page behaves the same way. I had two static redirects set up. Once I select both and delete them, they disappear correctly, but the list still shows them as being selected:

![image](https://user-images.githubusercontent.com/1250017/124746699-d8453700-df29-11eb-9ddc-108797b400b2.png)

I'm guessing this is also doing the same thing on the Statistics page. Something in Vue thinks a search has been performed and is showing no results, but there's no way to reset it and show all results again.

**Just tested 3.1.54 and that works fine, but breaks when you update to 3.1.55**

**Comment by khalwat** [comment]
Click on the Reset button to clear the filter. It's a bug that's already been fixed, see https://github.com/nystudio107/craft-retour/issues/190

**Comment by darylknight** [comment]
There is no reset button, the search bar doesn't appear:

![image](https://user-images.githubusercontent.com/1250017/124762679-d7b59c00-df3b-11eb-88a0-ec426927563a.png)

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/000bb4acd01d5506138348d955c8c099b4146ec8

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.56”,
```
Then do a `composer clear-cache && composer update`

**Comment by khalwat** [comment]
Released as 3.1.56 -> https://github.com/nystudio107/craft-retour/releases/tag/3.1.56

**Comment by darylknight** [comment]
This isn't working quite right still:

- Land on the page (which is pre-filtered to yesterday's search query)
- Hit reset. All results are displayed
- Select and delete on statistic
- All the other results disappear until you hit Reset again

**Comment by khalwat** [comment]
Are you able to consistently reproduce this? I can't here

**Comment by darylknight** [comment]
No, looks like installing it on my boilerplate works ok. However, I've updated the plugin and cleared both sets of caches on the site it is broken on, and it's still happening. Also still seeing this on that site:

![image](https://user-images.githubusercontent.com/1250017/124915668-7a345480-dffa-11eb-8eb6-455ef58256c5.png)

Is there anything else I can clear? Should I just re-install it?

**Comment by khalwat** [comment]
I have an idea, it's probably timing-related, let me give something a shot here... hang on a minute

**Comment by khalwat** [comment]
Addressed in: https://github.com/nystudio107/craft-retour/commit/daf18878a17e32b87a1531cb07552123f29a4c8d

You can try it now by setting your semver in your `composer.json` to look like this:
```json
    "nystudio107/craft-retour": "dev-develop as 3.1.57”,
```
Then do a `composer clear-cache && composer update`

**Comment by darylknight** [comment]
Sorry, doesn't seem to have changed anything. If I go to the dashboard, I get no results. Hitting **Reset** shows me all results correctly, then if I refresh the page they all disappear again. Utilities > System report is showing **Retour | dev-develop**

**Comment by khalwat** [comment]
In Retour -> Preferences what is the refresh time set to? If you set it to Never, does it change anything?

**Comment by darylknight** [comment]
I've changed it from the default 5 secs to never; still happening.
Also nuked composer, uninstalled Retour, pushed, re-installed 3.1.57-dev then redeployed. Seems to work ok on local - only the production site is still broken. Local site doesn't show that vue pagination warning, production site does.

**Comment by khalwat** [comment]
Very odd. Okay I'll see what I can find. The production and local sites in question are operating on the same db?

**Comment by darylknight** [comment]
Yes. I just used Craft Scripts to pull the production database to local, and it's working fine locally

**Comment by khalwat** [comment]
Try clearing local storage in your browser, or using a different browser altogether to see if it isn't stale cached data?

**Comment by darylknight** [comment]
Yep, looks like clearing local storage solved the issue; and the warning has disappeared now too - thank you!

**Comment by khalwat** [comment]
Released as 3.1.57 -> https://github.com/nystudio107/craft-retour/releases/tag/3.1.57
